# Generated by Django 3.0.4 on 2020-03-26 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('kind', models.CharField(blank=True, choices=[('VO', 'Volunteer'), ('SH', 'At-Risk Sheltered')], max_length=2)),
                ('is_publicly_visible', models.BooleanField(default=True)),
                ('contact_preference', models.CharField(blank=True, choices=[('EM', 'Email'), ('PH', 'Phone')], max_length=2)),
                ('contact_details', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', related_query_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_place_id', models.CharField(db_index=True, max_length=512)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', related_query_name='location', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_location',
            },
        ),
    ]
